#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one-time Google Cloud setup for COA Audit Explorer.
#
# Safe to re-run: every step checks whether its resource already exists and
# skips it. Run from anywhere; the script moves to the repo root first.
#
# Produces:
#   .env (git-ignored)  GCP_PROJECT_ID, GCP_REGION, GEMINI_LOCATION,
#                       GEMINI_ANSWER_MODEL, GEMINI_JUDGE_MODEL,
#                       GEMINI_EMBEDDING_MODEL, FIRESTORE_DATABASE, FIRESTORE_LOG_COLLECTION,
#                       FIRESTORE_TTL_FIELD, ARTIFACT_REPOSITORY (see .env.example)
#   GitHub Actions variables (no secrets, no JSON keys):
#                       GCP_PROJECT_ID, GCP_REGION,
#                       GCP_WORKLOAD_IDENTITY_PROVIDER,
#                       GCP_DEPLOYER_SERVICE_ACCOUNT,
#                       GCP_RUNTIME_SERVICE_ACCOUNT, GCP_ARTIFACT_REPOSITORY
# ──────────────────────────────────────────────────────────────────────────

# Git Bash on Windows rewrites arguments that look like POSIX paths
# (e.g. principalSet://iam.googleapis.com/...); switch that off.
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'

cd "$(dirname "${BASH_SOURCE[0]}")/.."

TOTAL_STAGES=10

REGION="us-central1"
RUNTIME_SA_ID="coa-runtime"
DEPLOYER_SA_ID="coa-deployer"
AR_REPO="coa-explorer"
WIF_POOL="github"
WIF_PROVIDER="github-actions"
FIRESTORE_DB="coa-explorer"   # named database, so a shared project's (default) database is never touched
LOG_COLLECTION="questions"
LIMITS_COLLECTION="limits"   # rate-limit and daily-cap counters; expire like the log
TTL_FIELD="expire_at"
TRIAL_END="2026-12-01"

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# retry N cmd... re-runs a command that may fail while IAM changes propagate.
retry() {
  local tries="$1" n=1; shift
  until "$@"; do
    (( n >= tries )) && return 1
    n=$((n + 1)); sleep 4
  done
}

# ask_default KEY "Prompt" DEFAULT: like ask, but an empty first-run answer
# takes DEFAULT.
ask_default() {
  local key="$1" prompt="$2" default="$3"
  note "Default: $default"
  ask "$key" "$prompt"
  [[ -n "${!key}" ]] || printf -v "$key" '%s' "$default"
}

banner "COA Audit Explorer · Google Cloud setup"

# ── 1. Sign in ────────────────────────────────────────────────────────────
stage "Sign in to gcloud and GitHub"
say "You need three logins: gcloud (to run this wizard), Application Default"
say "Credentials (so your local code can call Gemini), and the GitHub CLI."
command -v gcloud >/dev/null 2>&1 || die "gcloud not found. Install: https://cloud.google.com/sdk/docs/install"
command -v gh     >/dev/null 2>&1 || die "gh not found. Install: https://cli.github.com"
command -v curl   >/dev/null 2>&1 || die "curl not found."

if [[ -z "$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null)" ]]; then
  step "A browser window will ask you to sign in to the Google account that owns the project."
  gcloud auth login
else
  say "✓ gcloud: signed in as $(gcloud auth list --filter=status:ACTIVE --format='value(account)')"
fi

if ! gcloud auth application-default print-access-token >/dev/null 2>&1; then
  step "Sign in again for Application Default Credentials (used by local code)."
  gcloud auth application-default login
else
  say "✓ Application Default Credentials present"
fi

if ! gh auth status >/dev/null 2>&1; then
  step "Sign in to GitHub; choose HTTPS and the browser flow when asked."
  gh auth login
else
  say "✓ gh: signed in"
fi

GITHUB_REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)
if [[ -z "$GITHUB_REPO" ]]; then
  ask GITHUB_REPO "GitHub repository (owner/name):"
fi
[[ "$GITHUB_REPO" == */* ]] || die "Repository must look like owner/name, got '$GITHUB_REPO'."
export GH_REPO="$GITHUB_REPO"   # gh (and set_var) target this repo regardless of cwd
say "✓ GitHub repository: $GITHUB_REPO"
pause "Press Enter to continue."

# ── 2. Project ────────────────────────────────────────────────────────────
stage "Choose the Google Cloud project"
say "Use the project that holds your \$300 Free Trial credit. If you don't have"
say "one yet, create it first (any ID, e.g. coa-audit-explorer)."
open_url "https://console.cloud.google.com/projectcreate"
step "Create the project (or skip if it exists) and note its Project ID."
ask GCP_PROJECT_ID "Project ID:"
[[ -n "$GCP_PROJECT_ID" ]] || die "A project ID is required."
gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1 \
  || die "Can't see project '$GCP_PROJECT_ID'. Check the ID and that you're signed in to the right account."
gcloud config set project "$GCP_PROJECT_ID" >/dev/null 2>&1
PROJECT_NUMBER=$(gcloud projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)') \
  || die "Couldn't read the project number for $GCP_PROJECT_ID."

billing_enabled() {
  [[ "$(gcloud billing projects describe "$GCP_PROJECT_ID" --format='value(billingEnabled)' 2>/dev/null)" == "True" ]]
}
if ! billing_enabled; then
  warn "No billing account is linked to $GCP_PROJECT_ID. APIs and budgets need one."
  open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GCP_PROJECT_ID"
  step "Link your Free Trial billing account to the project, then come back."
  pause "Press Enter once it's linked."
  billing_enabled || die "Billing still isn't linked to $GCP_PROJECT_ID."
fi
say "✓ Project $GCP_PROJECT_ID (number $PROJECT_NUMBER) with billing enabled"
pause "Press Enter to continue."

# ── 3. APIs ───────────────────────────────────────────────────────────────
stage "Enable APIs"
say "Enabling the APIs the app, CI and this wizard rely on (already-enabled ones are skipped)."
note "Vertex AI, Document AI, Firestore, Cloud Run, Artifact Registry, Cloud Build, IAM Credentials,"
note "plus IAM, Security Token Service, Resource Manager and Billing Budgets for the steps below."
gcloud services enable \
  aiplatform.googleapis.com \
  documentai.googleapis.com \
  firestore.googleapis.com \
  run.googleapis.com \
  artifactregistry.googleapis.com \
  cloudbuild.googleapis.com \
  iamcredentials.googleapis.com \
  iam.googleapis.com \
  sts.googleapis.com \
  cloudresourcemanager.googleapis.com \
  billingbudgets.googleapis.com \
  --project "$GCP_PROJECT_ID"
say "✓ APIs enabled"
pause "Press Enter to continue."

# ── 4. Service accounts ───────────────────────────────────────────────────
stage "Create service accounts"
RUNTIME_SA="$RUNTIME_SA_ID@$GCP_PROJECT_ID.iam.gserviceaccount.com"
DEPLOYER_SA="$DEPLOYER_SA_ID@$GCP_PROJECT_ID.iam.gserviceaccount.com"

ensure_sa() {
  local id="$1" email="$2" display="$3"
  if gcloud iam service-accounts describe "$email" --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
    say "✓ $email already exists"
  else
    gcloud iam service-accounts create "$id" --display-name="$display" --project "$GCP_PROJECT_ID"
    say "✓ created $email"
  fi
}
grant_project_role() {
  local email="$1" role="$2"
  retry 5 gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member="serviceAccount:$email" --role="$role" --condition=None >/dev/null \
    || die "Couldn't grant $role to $email."
  say "✓ $email → $role"
}

say "Runtime account: what the deployed app runs as (calls Gemini, writes the question log)."
ensure_sa "$RUNTIME_SA_ID" "$RUNTIME_SA" "COA Explorer runtime"
grant_project_role "$RUNTIME_SA" roles/aiplatform.user
# Firestore access is limited to the app's own database by an IAM condition, so the runtime
# account can't read other apps' data in the same project.
FIRESTORE_CONDITION="expression=resource.name == 'projects/$GCP_PROJECT_ID/databases/$FIRESTORE_DB',title=$FIRESTORE_DB-database-only"
retry 5 gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
  --member="serviceAccount:$RUNTIME_SA" --role=roles/datastore.user \
  --condition="$FIRESTORE_CONDITION" >/dev/null \
  || die "Couldn't grant Firestore access to $RUNTIME_SA."
say "✓ $RUNTIME_SA → roles/datastore.user on database '$FIRESTORE_DB' only"

printf '\n'
say "Deployer account: what GitHub Actions impersonates to deploy."
ensure_sa "$DEPLOYER_SA_ID" "$DEPLOYER_SA" "COA Explorer CI deployer"
grant_project_role "$DEPLOYER_SA" roles/run.admin
grant_project_role "$DEPLOYER_SA" roles/artifactregistry.writer
# Service Account User is scoped to the runtime account only, so CI can deploy
# a service that runs as it but can't act as any other account.
retry 5 gcloud iam service-accounts add-iam-policy-binding "$RUNTIME_SA" \
  --member="serviceAccount:$DEPLOYER_SA" --role=roles/iam.serviceAccountUser \
  --project "$GCP_PROJECT_ID" >/dev/null \
  || die "Couldn't let $DEPLOYER_SA act as $RUNTIME_SA."
say "✓ $DEPLOYER_SA → roles/iam.serviceAccountUser on $RUNTIME_SA"
pause "Press Enter to continue."

# ── 5. Artifact Registry ──────────────────────────────────────────────────
stage "Create the container image repository"
say "CI pushes the app's container image here before deploying it to Cloud Run."
if gcloud artifacts repositories describe "$AR_REPO" --location="$REGION" --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  say "✓ repository '$AR_REPO' already exists in $REGION"
else
  gcloud artifacts repositories create "$AR_REPO" --repository-format=docker --location="$REGION" \
    --description="COA Audit Explorer container images" --project "$GCP_PROJECT_ID" \
    || die "Couldn't create the Artifact Registry repository."
  say "✓ created Docker repository '$AR_REPO' in $REGION"
fi
AR_IMAGE_PREFIX="$REGION-docker.pkg.dev/$GCP_PROJECT_ID/$AR_REPO"
say "Images go under: $AR_IMAGE_PREFIX/<image>:<tag>"
note "The deployer account can already push here (Artifact Registry Writer, granted in stage 4)."
note "Storage beyond 0.5 GB is billed (about \$0.10/GB-month); the image is small."
set_var GCP_ARTIFACT_REPOSITORY "$AR_REPO"
pause "Press Enter to continue."

# ── 6. Workload Identity Federation ───────────────────────────────────────
stage "Let GitHub Actions authenticate without keys"
say "Workload Identity Federation: GitHub proves who it is with a short-lived token,"
say "and only $GITHUB_REPO may impersonate the deployer account."

if gcloud iam workload-identity-pools describe "$WIF_POOL" --location=global --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  say "✓ pool '$WIF_POOL' already exists"
else
  gcloud iam workload-identity-pools create "$WIF_POOL" --location=global \
    --display-name="GitHub Actions" --project "$GCP_PROJECT_ID"
  say "✓ created pool '$WIF_POOL'"
fi

if gcloud iam workload-identity-pools providers describe "$WIF_PROVIDER" \
     --workload-identity-pool="$WIF_POOL" --location=global --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  # Keep the repository restriction in sync if the repo was typed differently on a re-run.
  gcloud iam workload-identity-pools providers update-oidc "$WIF_PROVIDER" \
    --workload-identity-pool="$WIF_POOL" --location=global \
    --attribute-condition="assertion.repository=='$GITHUB_REPO'" \
    --project "$GCP_PROJECT_ID" >/dev/null \
    || die "Couldn't update provider '$WIF_PROVIDER'."
  say "✓ provider '$WIF_PROVIDER' already exists (restricted to $GITHUB_REPO)"
else
  retry 5 gcloud iam workload-identity-pools providers create-oidc "$WIF_PROVIDER" \
    --workload-identity-pool="$WIF_POOL" --location=global \
    --issuer-uri="https://token.actions.githubusercontent.com" \
    --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository" \
    --attribute-condition="assertion.repository=='$GITHUB_REPO'" \
    --display-name="GitHub Actions" --project "$GCP_PROJECT_ID" \
    || die "Couldn't create the OIDC provider."
  say "✓ created provider '$WIF_PROVIDER' (restricted to $GITHUB_REPO)"
fi

WIF_PROVIDER_NAME=$(gcloud iam workload-identity-pools providers describe "$WIF_PROVIDER" \
  --workload-identity-pool="$WIF_POOL" --location=global --project "$GCP_PROJECT_ID" --format='value(name)') \
  || die "Couldn't read the provider's resource name."
WIF_PRINCIPAL="principalSet://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/$WIF_POOL/attribute.repository/$GITHUB_REPO"

retry 5 gcloud iam service-accounts add-iam-policy-binding "$DEPLOYER_SA" \
  --member="$WIF_PRINCIPAL" --role=roles/iam.workloadIdentityUser \
  --project "$GCP_PROJECT_ID" >/dev/null \
  || die "Couldn't allow GitHub to impersonate $DEPLOYER_SA."
say "✓ $GITHUB_REPO may impersonate $DEPLOYER_SA"

printf '\n'
say "Saving the identifiers as GitHub Actions variables (they are not secrets):"
set_var GCP_PROJECT_ID "$GCP_PROJECT_ID"
set_var GCP_REGION "$REGION"
set_var GCP_WORKLOAD_IDENTITY_PROVIDER "$WIF_PROVIDER_NAME"
set_var GCP_DEPLOYER_SERVICE_ACCOUNT "$DEPLOYER_SA"
set_var GCP_RUNTIME_SERVICE_ACCOUNT "$RUNTIME_SA"
pause "Press Enter to continue."

# ── 7. Firestore ──────────────────────────────────────────────────────────
stage "Create Firestore and the 30-day log expiry"
say "The app gets its own named database '$FIRESTORE_DB', separate from the project's (default) one."
if gcloud firestore databases describe --database="$FIRESTORE_DB" --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  existing_loc=$(gcloud firestore databases describe --database="$FIRESTORE_DB" --project "$GCP_PROJECT_ID" --format='value(locationId)') \
    || die "Couldn't read the location of database '$FIRESTORE_DB'."
  say "✓ database '$FIRESTORE_DB' already exists in $existing_loc"
  [[ "$existing_loc" == "$REGION" ]] || warn "Expected $REGION. A database's location can't be changed; the app will still work but Cloud Run is planned for $REGION."
else
  say "Creating database '$FIRESTORE_DB' in $REGION, native mode..."
  gcloud firestore databases create --database="$FIRESTORE_DB" --location="$REGION" --type=firestore-native \
    --project "$GCP_PROJECT_ID" >/dev/null || die "Couldn't create the Firestore database."
  say "✓ database created"
fi

say "Enabling TTL: documents in '$LOG_COLLECTION' are deleted once their '$TTL_FIELD' timestamp passes."
gcloud firestore fields ttls update "$TTL_FIELD" --collection-group="$LOG_COLLECTION" \
  --enable-ttl --async --database="$FIRESTORE_DB" --project "$GCP_PROJECT_ID" >/dev/null 2>&1 \
  && say "✓ TTL policy requested (Firestore finishes applying it in the background, up to ~30 min)" \
  || { warn "Couldn't (re)apply the TTL policy; it may already be enabled or still being created."
       SKIPPED+=("Check the TTL policy: gcloud firestore fields ttls list --database=$FIRESTORE_DB"); }
say "Enabling TTL on '$LIMITS_COLLECTION' too: the hashed-IP and daily counters expire within hours."
gcloud firestore fields ttls update "$TTL_FIELD" --collection-group="$LIMITS_COLLECTION" \
  --enable-ttl --async --database="$FIRESTORE_DB" --project "$GCP_PROJECT_ID" >/dev/null 2>&1 \
  && say "✓ TTL policy requested for '$LIMITS_COLLECTION'" \
  || { warn "Couldn't (re)apply the TTL policy on '$LIMITS_COLLECTION'; it may already be enabled."
       SKIPPED+=("Check the TTL policies: gcloud firestore fields ttls list --database=$FIRESTORE_DB"); }
note "The app writes '$TTL_FIELD' = question time + 30 days on every logged question, and a"
note "short expiry on every counter."
pause "Press Enter to continue."

# ── 8. Budget alerts ──────────────────────────────────────────────────────
stage "Budget alerts at \$5, \$10 and \$20"
BUDGET_NAME="coa-audit-explorer-$GCP_PROJECT_ID"
BILLING_ID=$(gcloud billing projects describe "$GCP_PROJECT_ID" --format='value(billingAccountName)') \
  || die "Couldn't read the billing account for $GCP_PROJECT_ID."
BILLING_ID="${BILLING_ID#billingAccounts/}"

# Tell "no budget yet" apart from "couldn't list", so a failed check never creates a duplicate.
# gcloud prints "Listed 0 items." on stderr, so keep stderr out of the captured stdout.
LIST_FAILED=0
LIST_ERR_FILE=$(mktemp)
EXISTING_BUDGETS=$(gcloud billing budgets list --billing-account="$BILLING_ID" \
  --filter="displayName=\"$BUDGET_NAME\"" --format='value(name)' 2>"$LIST_ERR_FILE") || LIST_FAILED=1
LIST_ERR=$(cat "$LIST_ERR_FILE"); rm -f "$LIST_ERR_FILE"

if (( LIST_FAILED )); then
  warn "Couldn't list budgets: $LIST_ERR"
  SKIPPED+=("Budget alerts: couldn't check for an existing budget; verify in the Billing console")
elif [[ -n "$EXISTING_BUDGETS" ]]; then
  say "✓ budget '$BUDGET_NAME' already exists"
elif BUDGET_ERR=$(gcloud billing budgets create --billing-account="$BILLING_ID" \
       --display-name="$BUDGET_NAME" \
       --filter-projects="projects/$GCP_PROJECT_ID" \
       --budget-amount=20USD \
       --credit-types-treatment=exclude-all-credits \
       --threshold-rule=percent=0.25 \
       --threshold-rule=percent=0.5 \
       --threshold-rule=percent=1.0 2>&1 >/dev/null); then
  say "✓ created a \$20 budget that emails billing admins at \$5, \$10 and \$20"
  note "Free Trial credit is excluded, so alerts track gross spend rather than what you pay."
else
  warn "Couldn't create the budget: $BUDGET_ERR"
  warn "It needs Billing Account Administrator and a USD billing account. Create it by hand:"
  open_url "https://console.cloud.google.com/billing/$BILLING_ID/budgets"
  step "Create budget → scope: project $GCP_PROJECT_ID → amount: \$20 → exclude credits → alerts at 25%, 50%, 100%."
  SKIPPED+=("Budget alerts at \$5/\$10/\$20 (create in the Billing console)")
fi
note "Budget alerts only notify; they don't stop spending. Cloud Run max-instances and the app's"
note "daily cap are the real limits."
pause "Press Enter to continue."

# ── 9. Local settings and Gemini check ────────────────────────────────────
stage "Write local settings and test Gemini"
say "Saving non-secret settings to .env (git-ignored; .env.example shows the shape)."
note "Model names live in config so you can compare models without code changes."
GEMINI_EMBEDDING_MODEL="gemini-embedding-001"

# Google retires Gemini models often, so each model is called live before it's saved.
ADC_TOKEN=$(gcloud auth application-default print-access-token 2>/dev/null || true)
vertex_curl() {
  curl -s -H "Authorization: Bearer $ADC_TOKEN" -H "x-goog-user-project: $GCP_PROJECT_ID" \
    -H "Content-Type: application/json" "$@"
}
gemini_http_code() {
  vertex_curl -o /dev/null -w '%{http_code}' -X POST \
    "https://aiplatform.googleapis.com/v1/projects/$GCP_PROJECT_ID/locations/global/publishers/google/models/$1:generateContent" \
    -d '{"contents":[{"role":"user","parts":[{"text":"Reply with the single word: ok"}]}]}' || true
}
list_gemini_models() {
  vertex_curl "https://aiplatform.googleapis.com/v1beta1/publishers/google/models?pageSize=200" 2>/dev/null \
    | grep -o 'publishers/google/models/gemini[A-Za-z0-9._-]*' | sed 's|.*/||' | sort -u | tr '\n' ' ' || true
}
# pick_model KEY "Prompt" DEFAULT asks for a model ID and keeps asking until Vertex serves it
# (or you choose to keep it anyway).
pick_model() {
  local key="$1" prompt="$2" default="$3" code models input
  ask_default "$key" "$prompt" "$default"
  # A model ID looks like gemini-3.8-flash. Reject anything else without echoing it, since a
  # pasted API key must never be written to .env.
  while [[ ! "${!key}" =~ ^gemini-[a-z0-9.-]+$ ]]; do
    warn "That doesn't look like a model ID (expected e.g. $default). Don't paste API keys here."
    printf '  %sModel ID: %s' "$BOLD" "$RESET"
    read -r input || true
    printf -v "$key" '%s' "${input:-$default}"
  done
  while :; do
    code=$(gemini_http_code "${!key}")
    if [[ "$code" == "200" ]]; then say "✓ ${!key} answered (HTTP 200)"; return; fi
    warn "${!key} returned HTTP ${code:-none}."
    if [[ "$code" == "404" ]]; then
      models=$(list_gemini_models)
      [[ -n "$models" ]] && note "Gemini models Vertex lists for your project: $models"
      printf '  %sType another model ID to try, or press Enter to keep %s: %s' "$BOLD" "${!key}" "$RESET"
      read -r input || true
      if [[ -n "$input" ]]; then printf -v "$key" '%s' "$input"; continue; fi
    else
      warn "Not a missing model; if it's 403, wait a minute for the API enablement to propagate."
    fi
    SKIPPED+=("Confirm $key=${!key} works (re-run scripts/setup-gcp.sh)")
    return
  done
}

note "Answer model: Gemini 3.8 Flash is the current GA Flash. 2.5 models are being retired."
pick_model GEMINI_ANSWER_MODEL "Answer model (Gemini Flash):" "gemini-3.8-flash"
note "Judge model: the newest Pro is still a preview; there is no newer GA Pro than the retiring 2.5."
pick_model GEMINI_JUDGE_MODEL "Evaluation judge model (Gemini Pro):" "gemini-3.1-pro-preview"

write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_REGION "$REGION"
write_env GEMINI_LOCATION "global"
write_env GEMINI_ANSWER_MODEL "$GEMINI_ANSWER_MODEL"
write_env GEMINI_JUDGE_MODEL "$GEMINI_JUDGE_MODEL"
write_env GEMINI_EMBEDDING_MODEL "$GEMINI_EMBEDDING_MODEL"
write_env FIRESTORE_DATABASE "$FIRESTORE_DB"
write_env FIRESTORE_LOG_COLLECTION "$LOG_COLLECTION"
write_env FIRESTORE_TTL_FIELD "$TTL_FIELD"
write_env ARTIFACT_REPOSITORY "$AR_REPO"

pause "Press Enter to continue."

# ── 10. Free Trial reminder ────────────────────────────────────────────────
stage "Before you finish: upgrade from the Free Trial"
warn "Your Free Trial ends around $TRIAL_END. After that, resources are stopped and"
warn "later deleted unless the account is upgraded to a paid account."
say "Upgrading doesn't charge you by itself, and the \$300 credit stays until it expires."
say "With the daily cap, scale-to-zero and max 2 instances, expect close to \$0 when idle."
open_url "https://console.cloud.google.com/billing"
step "Open your billing account → click 'Activate' / 'Upgrade' in the Free Trial banner."
note "Put a reminder in your calendar for a week before $TRIAL_END."
pause "Press Enter to finish."

finish
