#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: one-time Google Cloud setup for COA Audit Explorer.
#
# Safe to re-run: every step checks whether its resource already exists and
# skips it. Run from anywhere; the script moves to the repo root first.
#
# Produces:
#   .env (git-ignored)  GCP_PROJECT_ID, GCP_REGION, GEMINI_LOCATION,
#                       GEMINI_ANSWER_MODEL, GEMINI_JUDGE_MODEL,
#                       GEMINI_EMBEDDING_MODEL, FIRESTORE_LOG_COLLECTION,
#                       FIRESTORE_TTL_FIELD   (see .env.example)
#   GitHub Actions variables (no secrets, no JSON keys):
#                       GCP_PROJECT_ID, GCP_REGION,
#                       GCP_WORKLOAD_IDENTITY_PROVIDER,
#                       GCP_DEPLOYER_SERVICE_ACCOUNT,
#                       GCP_RUNTIME_SERVICE_ACCOUNT
# ──────────────────────────────────────────────────────────────────────────

# Git Bash on Windows rewrites arguments that look like POSIX paths
# (e.g. principalSet://iam.googleapis.com/...); switch that off.
export MSYS_NO_PATHCONV=1 MSYS2_ARG_CONV_EXCL='*'

cd "$(dirname "${BASH_SOURCE[0]}")/.."

TOTAL_STAGES=9

REGION="us-central1"
RUNTIME_SA_ID="coa-runtime"
DEPLOYER_SA_ID="coa-deployer"
WIF_POOL="github"
WIF_PROVIDER="github-actions"
LOG_COLLECTION="questions"
TTL_FIELD="expire_at"
TRIAL_END="2026-12-01"

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2; exit 1; }

# retry N cmd... re-runs a command that may fail while IAM changes propagate.
retry() {
  local tries="$1" n=1; shift
  until "$@"; do
    (( n >= tries )) && return 1
    n=$((n + 1)); sleep 4
  done
}

# ask_default KEY "Prompt" DEFAULT: like ask, but an empty first-run answer
# takes DEFAULT.
ask_default() {
  local key="$1" prompt="$2" default="$3"
  note "Default: $default"
  ask "$key" "$prompt"
  [[ -n "${!key}" ]] || printf -v "$key" '%s' "$default"
}

banner "COA Audit Explorer · Google Cloud setup"

# ── 1. Sign in ────────────────────────────────────────────────────────────
stage "Sign in to gcloud and GitHub"
say "You need three logins: gcloud (to run this wizard), Application Default"
say "Credentials (so your local code can call Gemini), and the GitHub CLI."
command -v gcloud >/dev/null 2>&1 || die "gcloud not found. Install: https://cloud.google.com/sdk/docs/install"
command -v gh     >/dev/null 2>&1 || die "gh not found. Install: https://cli.github.com"
command -v curl   >/dev/null 2>&1 || die "curl not found."

if [[ -z "$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null)" ]]; then
  step "A browser window will ask you to sign in to the Google account that owns the project."
  gcloud auth login
else
  say "✓ gcloud: signed in as $(gcloud auth list --filter=status:ACTIVE --format='value(account)')"
fi

if ! gcloud auth application-default print-access-token >/dev/null 2>&1; then
  step "Sign in again for Application Default Credentials (used by local code)."
  gcloud auth application-default login
else
  say "✓ Application Default Credentials present"
fi

if ! gh auth status >/dev/null 2>&1; then
  step "Sign in to GitHub; choose HTTPS and the browser flow when asked."
  gh auth login
else
  say "✓ gh: signed in"
fi

GITHUB_REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)
if [[ -z "$GITHUB_REPO" ]]; then
  ask GITHUB_REPO "GitHub repository (owner/name):"
fi
[[ "$GITHUB_REPO" == */* ]] || die "Repository must look like owner/name, got '$GITHUB_REPO'."
say "✓ GitHub repository: $GITHUB_REPO"
pause "Press Enter to continue."

# ── 2. Project ────────────────────────────────────────────────────────────
stage "Choose the Google Cloud project"
say "Use the project that holds your \$300 Free Trial credit. If you don't have"
say "one yet, create it first (any ID, e.g. coa-audit-explorer)."
open_url "https://console.cloud.google.com/projectcreate"
step "Create the project (or skip if it exists) and note its Project ID."
ask GCP_PROJECT_ID "Project ID:"
[[ -n "$GCP_PROJECT_ID" ]] || die "A project ID is required."
gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1 \
  || die "Can't see project '$GCP_PROJECT_ID'. Check the ID and that you're signed in to the right account."
gcloud config set project "$GCP_PROJECT_ID" >/dev/null 2>&1
PROJECT_NUMBER=$(gcloud projects describe "$GCP_PROJECT_ID" --format='value(projectNumber)')

billing_enabled() {
  [[ "$(gcloud billing projects describe "$GCP_PROJECT_ID" --format='value(billingEnabled)' 2>/dev/null)" == "True" ]]
}
if ! billing_enabled; then
  warn "No billing account is linked to $GCP_PROJECT_ID. APIs and budgets need one."
  open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GCP_PROJECT_ID"
  step "Link your Free Trial billing account to the project, then come back."
  pause "Press Enter once it's linked."
  billing_enabled || die "Billing still isn't linked to $GCP_PROJECT_ID."
fi
say "✓ Project $GCP_PROJECT_ID (number $PROJECT_NUMBER) with billing enabled"
pause "Press Enter to continue."

# ── 3. APIs ───────────────────────────────────────────────────────────────
stage "Enable APIs"
say "Enabling the APIs the app, CI and this wizard rely on (already-enabled ones are skipped)."
note "Vertex AI, Document AI, Firestore, Cloud Run, Artifact Registry, Cloud Build, IAM Credentials,"
note "plus IAM, Security Token Service, Resource Manager and Billing Budgets for the steps below."
gcloud services enable \
  aiplatform.googleapis.com \
  documentai.googleapis.com \
  firestore.googleapis.com \
  run.googleapis.com \
  artifactregistry.googleapis.com \
  cloudbuild.googleapis.com \
  iamcredentials.googleapis.com \
  iam.googleapis.com \
  sts.googleapis.com \
  cloudresourcemanager.googleapis.com \
  billingbudgets.googleapis.com \
  --project "$GCP_PROJECT_ID"
say "✓ APIs enabled"
pause "Press Enter to continue."

# ── 4. Service accounts ───────────────────────────────────────────────────
stage "Create service accounts"
RUNTIME_SA="$RUNTIME_SA_ID@$GCP_PROJECT_ID.iam.gserviceaccount.com"
DEPLOYER_SA="$DEPLOYER_SA_ID@$GCP_PROJECT_ID.iam.gserviceaccount.com"

ensure_sa() {
  local id="$1" email="$2" display="$3"
  if gcloud iam service-accounts describe "$email" --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
    say "✓ $email already exists"
  else
    gcloud iam service-accounts create "$id" --display-name="$display" --project "$GCP_PROJECT_ID"
    say "✓ created $email"
  fi
}
grant_project_role() {
  local email="$1" role="$2"
  retry 5 gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member="serviceAccount:$email" --role="$role" --condition=None >/dev/null \
    || die "Couldn't grant $role to $email."
  say "✓ $email → $role"
}

say "Runtime account: what the deployed app runs as (calls Gemini, writes the question log)."
ensure_sa "$RUNTIME_SA_ID" "$RUNTIME_SA" "COA Explorer runtime"
grant_project_role "$RUNTIME_SA" roles/aiplatform.user
grant_project_role "$RUNTIME_SA" roles/datastore.user

printf '\n'
say "Deployer account: what GitHub Actions impersonates to deploy."
ensure_sa "$DEPLOYER_SA_ID" "$DEPLOYER_SA" "COA Explorer CI deployer"
grant_project_role "$DEPLOYER_SA" roles/run.admin
grant_project_role "$DEPLOYER_SA" roles/artifactregistry.writer
# Service Account User is scoped to the runtime account only, so CI can deploy
# a service that runs as it but can't act as any other account.
retry 5 gcloud iam service-accounts add-iam-policy-binding "$RUNTIME_SA" \
  --member="serviceAccount:$DEPLOYER_SA" --role=roles/iam.serviceAccountUser \
  --project "$GCP_PROJECT_ID" >/dev/null \
  || die "Couldn't let $DEPLOYER_SA act as $RUNTIME_SA."
say "✓ $DEPLOYER_SA → roles/iam.serviceAccountUser on $RUNTIME_SA"
pause "Press Enter to continue."

# ── 5. Workload Identity Federation ───────────────────────────────────────
stage "Let GitHub Actions authenticate without keys"
say "Workload Identity Federation: GitHub proves who it is with a short-lived token,"
say "and only $GITHUB_REPO may impersonate the deployer account."

if gcloud iam workload-identity-pools describe "$WIF_POOL" --location=global --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  say "✓ pool '$WIF_POOL' already exists"
else
  gcloud iam workload-identity-pools create "$WIF_POOL" --location=global \
    --display-name="GitHub Actions" --project "$GCP_PROJECT_ID"
  say "✓ created pool '$WIF_POOL'"
fi

if gcloud iam workload-identity-pools providers describe "$WIF_PROVIDER" \
     --workload-identity-pool="$WIF_POOL" --location=global --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  say "✓ provider '$WIF_PROVIDER' already exists"
else
  retry 5 gcloud iam workload-identity-pools providers create-oidc "$WIF_PROVIDER" \
    --workload-identity-pool="$WIF_POOL" --location=global \
    --issuer-uri="https://token.actions.githubusercontent.com" \
    --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository" \
    --attribute-condition="assertion.repository=='$GITHUB_REPO'" \
    --display-name="GitHub Actions" --project "$GCP_PROJECT_ID" \
    || die "Couldn't create the OIDC provider."
  say "✓ created provider '$WIF_PROVIDER' (restricted to $GITHUB_REPO)"
fi

WIF_PROVIDER_NAME=$(gcloud iam workload-identity-pools providers describe "$WIF_PROVIDER" \
  --workload-identity-pool="$WIF_POOL" --location=global --project "$GCP_PROJECT_ID" --format='value(name)')
WIF_PRINCIPAL="principalSet://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/$WIF_POOL/attribute.repository/$GITHUB_REPO"

retry 5 gcloud iam service-accounts add-iam-policy-binding "$DEPLOYER_SA" \
  --member="$WIF_PRINCIPAL" --role=roles/iam.workloadIdentityUser \
  --project "$GCP_PROJECT_ID" >/dev/null \
  || die "Couldn't allow GitHub to impersonate $DEPLOYER_SA."
say "✓ $GITHUB_REPO may impersonate $DEPLOYER_SA"

printf '\n'
say "Saving the identifiers as GitHub Actions variables (they are not secrets):"
set_var GCP_PROJECT_ID "$GCP_PROJECT_ID"
set_var GCP_REGION "$REGION"
set_var GCP_WORKLOAD_IDENTITY_PROVIDER "$WIF_PROVIDER_NAME"
set_var GCP_DEPLOYER_SERVICE_ACCOUNT "$DEPLOYER_SA"
set_var GCP_RUNTIME_SERVICE_ACCOUNT "$RUNTIME_SA"
pause "Press Enter to continue."

# ── 6. Firestore ──────────────────────────────────────────────────────────
stage "Create Firestore and the 30-day log expiry"
if gcloud firestore databases describe --database='(default)' --project "$GCP_PROJECT_ID" >/dev/null 2>&1; then
  existing_loc=$(gcloud firestore databases describe --database='(default)' --project "$GCP_PROJECT_ID" --format='value(locationId)')
  say "✓ Firestore database already exists in $existing_loc"
  [[ "$existing_loc" == "$REGION" ]] || warn "Expected $REGION. A database's location can't be changed; the app will still work but Cloud Run is planned for $REGION."
else
  say "Creating the (default) Firestore database in $REGION, native mode..."
  gcloud firestore databases create --location="$REGION" --type=firestore-native --project "$GCP_PROJECT_ID" \
    || die "Couldn't create the Firestore database."
  say "✓ database created"
fi

say "Enabling TTL: documents in '$LOG_COLLECTION' are deleted once their '$TTL_FIELD' timestamp passes."
gcloud firestore fields ttls update "$TTL_FIELD" --collection-group="$LOG_COLLECTION" \
  --enable-ttl --async --database='(default)' --project "$GCP_PROJECT_ID" >/dev/null \
  || die "Couldn't enable the TTL policy."
say "✓ TTL policy requested (Firestore finishes applying it in the background, up to ~30 min)"
note "The app must write '$TTL_FIELD' = question time + 30 days on every logged question."
pause "Press Enter to continue."

# ── 7. Budget alerts ──────────────────────────────────────────────────────
stage "Budget alerts at \$5, \$10 and \$20"
BUDGET_NAME="coa-audit-explorer-$GCP_PROJECT_ID"
BILLING_ID=$(gcloud billing projects describe "$GCP_PROJECT_ID" --format='value(billingAccountName)' | sed 's|^billingAccounts/||')

budget_exists() {
  [[ -n "$(gcloud billing budgets list --billing-account="$BILLING_ID" \
    --filter="displayName=$BUDGET_NAME" --format='value(name)' 2>/dev/null)" ]]
}

if budget_exists; then
  say "✓ budget '$BUDGET_NAME' already exists"
elif gcloud billing budgets create --billing-account="$BILLING_ID" \
       --display-name="$BUDGET_NAME" \
       --filter-projects="projects/$GCP_PROJECT_ID" \
       --budget-amount=20USD \
       --threshold-rule=percent=0.25 \
       --threshold-rule=percent=0.5 \
       --threshold-rule=percent=1.0 >/dev/null 2>&1; then
  say "✓ created a \$20 budget that emails billing admins at \$5, \$10 and \$20"
else
  warn "Couldn't create the budget from the command line (needs Billing Account Administrator,"
  warn "and a USD billing account). Create it by hand instead:"
  open_url "https://console.cloud.google.com/billing/$BILLING_ID/budgets"
  step "Create budget → scope: project $GCP_PROJECT_ID → amount: \$20 → alert thresholds 25%, 50%, 100%."
  SKIPPED+=("Budget alerts at \$5/\$10/\$20 (create in the Billing console)")
fi
note "Budget alerts only notify; they don't stop spending. Cloud Run max-instances and the app's"
note "daily cap are the real limits."
pause "Press Enter to continue."

# ── 8. Local settings and Gemini check ────────────────────────────────────
stage "Write local settings and test Gemini"
say "Saving non-secret settings to .env (git-ignored; .env.example shows the shape)."
note "Model names live in config so you can compare models without code changes."
ask_default GEMINI_ANSWER_MODEL "Answer model (Gemini Flash):" "gemini-2.5-flash"
ask_default GEMINI_JUDGE_MODEL "Evaluation judge model (Gemini Pro):" "gemini-2.5-pro"
GEMINI_EMBEDDING_MODEL="gemini-embedding-001"

write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
write_env GCP_REGION "$REGION"
write_env GEMINI_LOCATION "global"
write_env GEMINI_ANSWER_MODEL "$GEMINI_ANSWER_MODEL"
write_env GEMINI_JUDGE_MODEL "$GEMINI_JUDGE_MODEL"
write_env GEMINI_EMBEDDING_MODEL "$GEMINI_EMBEDDING_MODEL"
write_env FIRESTORE_LOG_COLLECTION "$LOG_COLLECTION"
write_env FIRESTORE_TTL_FIELD "$TTL_FIELD"

printf '\n'
say "Checking that your local credentials can call $GEMINI_ANSWER_MODEL on Vertex AI..."
TOKEN=$(gcloud auth application-default print-access-token 2>/dev/null || true)
HTTP_CODE=$(curl -s -o /dev/null -w '%{http_code}' \
  -X POST "https://aiplatform.googleapis.com/v1/projects/$GCP_PROJECT_ID/locations/global/publishers/google/models/$GEMINI_ANSWER_MODEL:generateContent" \
  -H "Authorization: Bearer $TOKEN" \
  -H "x-goog-user-project: $GCP_PROJECT_ID" \
  -H "Content-Type: application/json" \
  -d '{"contents":[{"role":"user","parts":[{"text":"Reply with the single word: ok"}]}]}' || true)
if [[ "$HTTP_CODE" == "200" ]]; then
  say "✓ Gemini answered (HTTP 200)"
else
  warn "Gemini call returned HTTP ${HTTP_CODE:-none}. If it's 404, the model name may be wrong for your"
  warn "project: check Vertex AI → Model Garden and edit GEMINI_ANSWER_MODEL in .env. If it's 403,"
  warn "wait a minute for the API enablement to propagate, then re-run this wizard."
  SKIPPED+=("Confirm local Gemini access (re-run scripts/setup-gcp.sh, or check GEMINI_ANSWER_MODEL in .env)")
fi
pause "Press Enter to continue."

# ── 9. Free Trial reminder ────────────────────────────────────────────────
stage "Before you finish: upgrade from the Free Trial"
warn "Your Free Trial ends around $TRIAL_END. After that, resources are stopped and"
warn "later deleted unless the account is upgraded to a paid account."
say "Upgrading doesn't charge you by itself, and the \$300 credit stays until it expires."
say "With the daily cap, scale-to-zero and max 2 instances, expect close to \$0 when idle."
open_url "https://console.cloud.google.com/billing"
step "Open your billing account → click 'Activate' / 'Upgrade' in the Free Trial banner."
note "Put a reminder in your calendar for a week before $TRIAL_END."
pause "Press Enter to finish."

finish
